apiVersion: v1
kind: Service
metadata:
  name: nginx
spec: 
  type: LoadBalancer
  selector:   # lables are used as selectors 
    app: nginx
    teir: frontend
    environment: deployment
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}